import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { AppAccountDock } from "@/app/_components/AppAccountDock";
import { mongolianLocalization } from "@/lib/clerk-auth-ui";
import "./globals.css";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl="/"
      localization={mongolianLocalization as never}
    >
      <html lang="en">
        <body className="antialiased">
          <AppAccountDock />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
