import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { AppAccountDock } from "@/app/_components/AppAccountDock";
import { mongolianLocalization } from "@/lib/clerk-auth-ui";
import { getCurrentDbUser } from "@/lib/auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dbUser = await getCurrentDbUser();
  const isAdmin = dbUser?.role === "ADMIN";

  return (
    <ClerkProvider
      afterSignOutUrl="/"
      localization={mongolianLocalization as never}
    >
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
          <script
            dangerouslySetInnerHTML={{
              __html: `
                try {
                  var savedTheme = window.localStorage.getItem("yume-theme");
                  var theme = savedTheme === "dark" || savedTheme === "light" ? savedTheme : "light";
                  document.documentElement.dataset.theme = theme;
                } catch (error) {}
              `,
            }}
          />
          <AppAccountDock isAdmin={isAdmin} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
